version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pooled-tenant-stack"
resolve_s3 = true
s3_prefix = "pooled-tenant"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
