version = 0.1
[default]
[default.build]
[default.build.parameters]
use_container = true

[default.deploy]
[default.deploy.parameters]
stack_name = "tenant-api"
resolve_s3 = true
s3_prefix = "tenant-api"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"